name: Block Direct Push to Main

on:
  push:
    branches:
      - main

jobs:
  prevent-direct-push:
    if: github.event_name == 'push' && github.actor != 'github-actions[bot]'
    runs-on: ubuntu-latest
    steps:
      - name: Fail if push is not from PR
        run: |
          echo "❌ Direct pushes to main are not allowed."
          exit 1
